# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spread-Messaging
version:      0.03
version_from: lib/Spread/Messaging.pm
installdirs:  site
requires:
    Exception::Class:              0
    Spread:                        3.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
